from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from smartshark_roles.config import ensure_project_directories, load_config, project_path
from smartshark_roles.io import dataframe_to_markdown, write_dataframe, write_text
from smartshark_roles.logging_utils import setup_logging


PILOT_PROJECT_NAMES = ["kafka", "nifi", "storm", "zeppelin", "zookeeper"]
SELECTED_COLUMNS = [
    "project_name",
    "project_id",
    "selection_reason",
    "n_issues",
    "n_closed_bug_issues",
    "n_issue_comments",
    "n_issue_events",
    "n_linked_commits",
    "n_commits",
    "n_pull_requests",
    "n_reviews",
    "n_actors_estimated",
    "usable_score",
]
METRIC_COLUMNS = [
    "n_issues",
    "n_closed_bug_issues",
    "n_issue_comments",
    "n_issue_events",
    "n_linked_commits",
    "n_commits",
    "n_pull_requests",
    "n_reviews",
    "n_actors_estimated",
    "usable_score",
]
MINIMUMS = {
    "n_closed_bug_issues": 100,
    "n_issue_comments": 1000,
    "n_issue_events": 1000,
    "n_linked_commits": 100,
    "n_commits": 500,
    "n_pull_requests": 100,
    "n_reviews": 100,
    "n_actors_estimated": 100,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create selected_projects.yaml from project availability results.")
    parser.add_argument("--config", default="configs/default.yaml", help="Path to the YAML config file.")
    parser.add_argument(
        "--availability-csv",
        default="reports/data_audit/project_source_availability.csv",
        help="Project source availability CSV generated by scripts/02_project_availability.py.",
    )
    parser.add_argument("--stage", default="pilot", help="Experiment stage label to write into selected_projects.yaml.")
    parser.add_argument("--candidate-count", type=int, default=10, help="Number of top projects to keep as candidates.")
    return parser.parse_args()


def read_availability(path: Path, logger: logging.Logger) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Project source availability CSV does not exist: {path}")
    frame = pd.read_csv(path)
    required = {"project_name", "project_id", *METRIC_COLUMNS}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(f"Availability CSV is missing required columns: {missing}")
    for column in METRIC_COLUMNS:
        frame[column] = pd.to_numeric(frame[column], errors="coerce").fillna(0)
    frame["project_name"] = frame["project_name"].astype(str)
    frame["project_id"] = frame["project_id"].astype(str)
    logger.info("Loaded availability CSV: %s (%d projects)", path, len(frame))
    return frame


def threshold_problems(row: pd.Series) -> list[str]:
    problems: list[str] = []
    for metric, minimum in MINIMUMS.items():
        if float(row.get(metric, 0)) < minimum:
            problems.append(f"{metric}={row.get(metric, 0)} below minimum {minimum}")
    return problems


def reason_for_selection(row: pd.Series) -> str:
    return (
        "Pilot target: strong bug-fixing lifecycle coverage with "
        f"{int(row['n_closed_bug_issues'])} closed bug issues, "
        f"{int(row['n_issue_comments'])} issue comments, "
        f"{int(row['n_issue_events'])} issue events, "
        f"{int(row['n_linked_commits'])} linked commits, "
        f"{int(row['n_pull_requests'])} pull requests, "
        f"{int(row['n_reviews'])} reviews, and "
        f"{int(row['n_actors_estimated'])} observed actors."
    )


def row_to_record(row: pd.Series, *, include_reason: bool) -> dict[str, Any]:
    record: dict[str, Any] = {
        "project_name": str(row["project_name"]),
        "project_id": str(row["project_id"]),
    }
    if include_reason:
        record["selection_reason"] = str(row["selection_reason"])
    for column in METRIC_COLUMNS:
        value = row[column]
        if column == "usable_score":
            record[column] = round(float(value), 3)
        else:
            record[column] = int(value)
    return record


def select_projects(
    availability: pd.DataFrame,
    logger: logging.Logger,
    candidate_count: int,
) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    warnings: list[str] = []
    selected_rows: list[pd.Series] = []
    availability_by_name = {
        str(row["project_name"]).lower(): row
        for _, row in availability.iterrows()
    }

    for project_name in PILOT_PROJECT_NAMES:
        row = availability_by_name.get(project_name.lower())
        if row is None:
            warning = f"Pilot candidate not found in availability CSV: {project_name}"
            warnings.append(warning)
            logger.warning(warning)
            continue

        problems = threshold_problems(row)
        if problems:
            warning = f"Pilot candidate has potential availability problems: {project_name}: {'; '.join(problems)}"
            warnings.append(warning)
            logger.warning(warning)
        selected_rows.append(row.copy())

    selected = pd.DataFrame(selected_rows)
    if not selected.empty:
        selected["selection_reason"] = selected.apply(reason_for_selection, axis=1)
        selected["pilot_order"] = selected["project_name"].map(
            {name: index for index, name in enumerate(PILOT_PROJECT_NAMES)}
        )
        selected = selected.sort_values("pilot_order").drop(columns=["pilot_order"])

    candidates = (
        availability.sort_values(["usable_score", "n_closed_bug_issues", "n_linked_commits"], ascending=False)
        .head(candidate_count)
        .copy()
    )
    return selected, candidates, warnings


def build_yaml_payload(
    config: dict[str, Any],
    selected: pd.DataFrame,
    candidates: pd.DataFrame,
    stage: str,
) -> dict[str, Any]:
    return {
        "experiment_stage": stage,
        "selection_date": datetime.now(timezone.utc).isoformat(),
        "selection_policy": {
            "purpose": "Pilot project selection before event extraction.",
            "pilot_target_count": len(PILOT_PROJECT_NAMES),
            "pilot_first_choice_projects": PILOT_PROJECT_NAMES,
            "candidate_pool": "Top projects by usable_score from reports/data_audit/project_source_availability.csv.",
            "criteria": [
                "closed bug issues are sufficient for lifecycle analysis",
                "issue comments and issue events are sufficient",
                "linked commits are available",
                "pull request and review data are available",
                "estimated actor count is not extremely small",
                "pilot set avoids using only the largest issue-heavy projects",
            ],
            "minimum_reference_thresholds": MINIMUMS,
        },
        "mongodb_database": config.get("mongodb", {}).get("database", "smartshark_2_2"),
        "selected_projects": [
            row_to_record(row, include_reason=True)
            for _, row in selected.iterrows()
        ],
        "candidate_projects": [
            row_to_record(row, include_reason=False)
            for _, row in candidates.iterrows()
        ],
    }


def write_yaml(payload: dict[str, Any], path: Path, logger: logging.Logger) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        logger.warning("Overwriting existing file: %s", path)
    with path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(payload, handle, sort_keys=False, allow_unicode=True)
    logger.info("Wrote YAML: %s", path)


def build_markdown_report(
    selected: pd.DataFrame,
    candidates: pd.DataFrame,
    warnings: list[str],
    config: dict[str, Any],
) -> str:
    selected_view = selected.loc[:, SELECTED_COLUMNS] if not selected.empty else selected
    candidate_cols = ["project_name", *METRIC_COLUMNS]
    lines = [
        "# Selected Projects",
        "",
        f"- Generated at UTC: `{datetime.now(timezone.utc).isoformat()}`",
        f"- MongoDB database: `{config.get('mongodb', {}).get('database', 'smartshark_2_2')}`",
        "- Experiment stage: `pilot`",
        "",
        "## Selection Policy",
        "",
        "The pilot experiment uses five first-choice projects: kafka, nifi, storm, zeppelin, and zookeeper. "
        "These projects provide substantial closed bug issues, issue discussions, issue lifecycle events, linked commits, "
        "pull request activity, review activity, and observed actors without taking only the largest issue-heavy projects.",
        "",
        "## Pilot Projects",
        "",
    ]
    lines.append(dataframe_to_markdown(selected_view) if not selected_view.empty else "No pilot projects were selected.")
    lines.extend(["", "## Candidate Projects", ""])
    lines.append(dataframe_to_markdown(candidates.loc[:, candidate_cols]) if not candidates.empty else "No candidate projects were recorded.")
    lines.extend(["", "## Warnings", ""])
    if warnings:
        lines.extend(f"- {warning}" for warning in warnings)
    else:
        lines.append("- No selection warnings.")
    lines.extend(
        [
            "",
            "## Next Step",
            "",
            "Proceed to events extraction for the selected pilot projects only. Do not run clustering before event and actor feature tables are built and audited.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    config = load_config(args.config)
    ensure_project_directories(config)

    log_path = ROOT / "reports" / "data_audit" / "logs" / f"select_projects_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.log"
    logger = setup_logging(log_path, level=logging.INFO)

    availability_path = project_path(args.availability_csv)
    selected_yaml_path = ROOT / "configs" / "selected_projects.yaml"
    selected_csv_path = ROOT / "reports" / "data_audit" / "selected_projects.csv"
    selected_md_path = ROOT / "reports" / "data_audit" / "selected_projects.md"

    try:
        availability = read_availability(availability_path, logger)
        selected, candidates, warnings = select_projects(availability, logger, args.candidate_count)
        yaml_payload = build_yaml_payload(config, selected, candidates, args.stage)

        write_yaml(yaml_payload, selected_yaml_path, logger)
        write_dataframe(selected.loc[:, SELECTED_COLUMNS], selected_csv_path, logger=logger)
        write_text(
            build_markdown_report(selected, candidates, warnings, config),
            selected_md_path,
            logger=logger,
        )
    except Exception:
        logger.exception("Project selection failed")
        return 1

    logger.info("Selected pilot projects: %s", ", ".join(selected["project_name"].tolist()))
    logger.info("Run next: .\\.venv\\Scripts\\python.exe scripts\\04_build_events.py --config configs\\default.yaml --selected-projects configs\\selected_projects.yaml")
    print("Generated:")
    print(f"- {selected_yaml_path}")
    print(f"- {selected_csv_path}")
    print(f"- {selected_md_path}")
    print("Next command after implementing events extraction:")
    print(r".\.venv\Scripts\python.exe scripts\04_build_events.py --config configs\default.yaml --selected-projects configs\selected_projects.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
