from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from smartshark_roles.io import dataframe_to_markdown, write_dataframe, write_text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit extracted SmartSHARK lifecycle events.")
    parser.add_argument("--events", required=True, help="Path to events CSV or Parquet file.")
    parser.add_argument(
        "--warnings",
        default="reports/build_events/event_extraction_warnings.csv",
        help="Warning CSV generated by event extraction.",
    )
    parser.add_argument(
        "--report",
        default="reports/build_events/events_smoke_quality_report.md",
        help="Markdown report path.",
    )
    parser.add_argument(
        "--counts",
        default="reports/build_events/events_smoke_quality_counts.csv",
        help="Quality counts CSV path.",
    )
    return parser.parse_args()


def resolve_output_paths(args: argparse.Namespace) -> tuple[Path, Path, Path, Path]:
    events_path = Path(args.events)
    warnings_path = Path(args.warnings)
    report_path = Path(args.report)
    counts_path = Path(args.counts)

    if not events_path.is_absolute():
        events_path = ROOT / events_path
    if not warnings_path.is_absolute():
        warnings_path = ROOT / warnings_path

    default_report = "reports/build_events/events_smoke_quality_report.md"
    default_counts = "reports/build_events/events_smoke_quality_counts.csv"
    if args.report == default_report and events_path.stem == "events":
        report_path = Path("reports/build_events/events_quality_report.md")
    if args.counts == default_counts and events_path.stem == "events":
        counts_path = Path("reports/build_events/events_quality_counts.csv")

    if not report_path.is_absolute():
        report_path = ROOT / report_path
    if not counts_path.is_absolute():
        counts_path = ROOT / counts_path
    return events_path, warnings_path, report_path, counts_path


def read_events(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Events file does not exist: {path}")
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)
    return pd.read_csv(path)


def read_warnings(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame(columns=["warning_type", "source", "event_type"])
    return pd.read_csv(path)


def count_rows(frame: pd.DataFrame, dimensions: list[str], label: str) -> pd.DataFrame:
    if frame.empty:
        return pd.DataFrame(columns=["section", *dimensions, "n_events"])
    grouped = frame.groupby(dimensions, dropna=False).size().reset_index(name="n_events")
    grouped.insert(0, "section", label)
    return grouped


def unknown_detail(events: pd.DataFrame) -> pd.DataFrame:
    unknown = events[events["lifecycle_stage"] == "unknown"].copy()
    if unknown.empty:
        return pd.DataFrame(columns=["section", "source", "event_type", "status_field", "n_events"])

    def status_field(value: str) -> str:
        try:
            metadata = json.loads(value) if isinstance(value, str) else {}
        except json.JSONDecodeError:
            metadata = {}
        return str(metadata.get("status_field", ""))

    unknown["status_field"] = unknown["metadata_json"].map(status_field)
    result = unknown.groupby(["source", "event_type", "status_field"], dropna=False).size().reset_index(name="n_events")
    result.insert(0, "section", "unknown_lifecycle_stage")
    return result.sort_values("n_events", ascending=False)


def warning_detail(warnings: pd.DataFrame) -> pd.DataFrame:
    if warnings.empty:
        return pd.DataFrame(columns=["section", "warning_type", "source", "event_type", "n_events"])
    result = warnings.groupby(["warning_type", "source", "event_type"], dropna=False).size().reset_index(name="n_events")
    result.insert(0, "section", "warnings")
    return result.sort_values("n_events", ascending=False)


def scalar_quality(events: pd.DataFrame) -> pd.DataFrame:
    total = len(events)
    duplicate_ids = int(events["event_id"].duplicated().sum()) if "event_id" in events else 0
    missing_timestamp = int(events["timestamp"].isna().sum()) if "timestamp" in events else 0
    missing_actor = int(events["actor_id_raw"].isna().sum()) if "actor_id_raw" in events else 0
    issue_linked = int((events["event_scope"] == "issue_linked").sum()) if "event_scope" in events else 0
    project_level = int((events["event_scope"] == "project_level").sum()) if "event_scope" in events else 0
    rows = [
        {"section": "overall", "metric": "total_events", "value": total, "rate": 1.0 if total else 0.0},
        {"section": "overall", "metric": "duplicate_event_ids", "value": duplicate_ids, "rate": duplicate_ids / total if total else 0.0},
        {"section": "overall", "metric": "missing_timestamp", "value": missing_timestamp, "rate": missing_timestamp / total if total else 0.0},
        {"section": "overall", "metric": "missing_actor_id_raw", "value": missing_actor, "rate": missing_actor / total if total else 0.0},
        {"section": "overall", "metric": "issue_linked_events", "value": issue_linked, "rate": issue_linked / total if total else 0.0},
        {"section": "overall", "metric": "project_level_events", "value": project_level, "rate": project_level / total if total else 0.0},
    ]
    return pd.DataFrame(rows)


def build_counts(events: pd.DataFrame, warnings: pd.DataFrame) -> pd.DataFrame:
    frames = [
        scalar_quality(events),
        count_rows(events, ["project_name"], "project"),
        count_rows(events, ["source"], "source"),
        count_rows(events, ["lifecycle_stage"], "lifecycle_stage"),
        count_rows(events, ["event_scope"], "event_scope"),
        count_rows(events, ["event_scope", "source"], "event_scope_source"),
        unknown_detail(events),
        warning_detail(warnings),
    ]
    return pd.concat(frames, ignore_index=True, sort=False)


def build_report(events: pd.DataFrame, warnings: pd.DataFrame, counts: pd.DataFrame, events_path: Path) -> str:
    total = len(events)
    duplicate_ids = int(events["event_id"].duplicated().sum())
    missing_timestamp = int(events["timestamp"].isna().sum())
    missing_actor = int(events["actor_id_raw"].isna().sum())
    project_counts = events.groupby("project_name").size().reset_index(name="n_events")
    source_counts = events.groupby("source").size().reset_index(name="n_events").sort_values("n_events", ascending=False)
    stage_counts = events.groupby("lifecycle_stage").size().reset_index(name="n_events").sort_values("n_events", ascending=False)
    scope_counts = events.groupby("event_scope").size().reset_index(name="n_events")
    unknown_counts = unknown_detail(events).drop(columns=["section"], errors="ignore").head(20)
    warning_counts = warning_detail(warnings).drop(columns=["section"], errors="ignore")
    title = "# Events Quality Report" if events_path.stem == "events" else "# Events Smoke Quality Report"

    lines = [
        title,
        "",
        f"- Generated at UTC: `{datetime.now(timezone.utc).isoformat()}`",
        f"- Events file: `{events_path}`",
        f"- Total events: `{total}`",
        f"- Duplicate event_id count: `{duplicate_ids}`",
        f"- Missing timestamp count/rate: `{missing_timestamp}` / `{missing_timestamp / total:.4f}`",
        f"- Missing actor_id_raw count/rate: `{missing_actor}` / `{missing_actor / total:.4f}`",
        "",
        "## Project Counts",
        "",
        dataframe_to_markdown(project_counts),
        "",
        "## Source Counts",
        "",
        dataframe_to_markdown(source_counts),
        "",
        "## Lifecycle Stage Counts",
        "",
        dataframe_to_markdown(stage_counts),
        "",
        "## Event Scope Counts",
        "",
        dataframe_to_markdown(scope_counts),
        "",
        "## Unknown Lifecycle Stage Detail",
        "",
        dataframe_to_markdown(unknown_counts) if not unknown_counts.empty else "No unknown lifecycle_stage rows.",
        "",
        "## Warning Counts",
        "",
        dataframe_to_markdown(warning_counts) if not warning_counts.empty else "No warnings.",
        "",
        "## Interpretation",
        "",
        "- `unknown` lifecycle rows are `event.issue_field_changed` records for heterogeneous JIRA fields such as remote links, issue links, fix versions, labels, sprint, summary, and story points.",
        "- These fields should remain `unknown` for now because mapping them wholesale to triage or workflow would mix unrelated semantics.",
        "- Timestamp and actor missingness is concentrated in `pull_request_review_comment`, matching the DB audit coverage for that collection.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    events_path, warnings_path, report_path, counts_path = resolve_output_paths(args)

    try:
        events = read_events(events_path)
        warnings = read_warnings(warnings_path)
        counts = build_counts(events, warnings)
        write_dataframe(counts, counts_path, logger=None)
        write_text(build_report(events, warnings, counts, events_path), report_path, logger=None)
    except Exception as exc:
        print(f"Event quality audit failed: {exc}", file=sys.stderr)
        return 1

    print(f"Quality audit succeeded: {len(events)} events")
    print(f"- {counts_path}")
    print(f"- {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
